import { AlumniProfile, FacultyProfile, InvestorProfile, Recommendation, StudentProfile } from "./types";

export const mockStudents: StudentProfile[] = [
  {
    id: "s1",
    user_id: "u1",
    role: "student",
    full_name: "Priya Sharma",
    email: "priya@university.edu",
    headline: "MBA Candidate | Aspiring Fintech Founder",
    bio: "Passionate about financial inclusion and building tech-first solutions for emerging markets.",
    location: "New York, NY",
    program: "MBA",
    graduation_year: 2026,
    career_goals: "Build a fintech startup focused on emerging market payments",
    industries_of_interest: ["Fintech", "Banking", "Emerging Markets"],
    skills: ["Product Strategy", "Financial Modeling", "Python", "UX Research"],
    startup_interest: true,
    internship_seeking: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "s2",
    user_id: "u2",
    role: "student",
    full_name: "Marcus Johnson",
    email: "marcus@university.edu",
    headline: "MBA Candidate | Healthcare Innovation",
    bio: "Former physician transitioning to healthcare tech. Focused on AI-driven diagnostics.",
    location: "Boston, MA",
    program: "MBA",
    graduation_year: 2026,
    career_goals: "Join or found a healthcare AI startup",
    industries_of_interest: ["HealthTech", "AI/ML", "Digital Health"],
    skills: ["Clinical Research", "Data Analysis", "Go-to-Market", "Fundraising"],
    startup_interest: true,
    internship_seeking: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockAlumni: AlumniProfile[] = [
  {
    id: "a1",
    user_id: "u3",
    role: "alumni",
    full_name: "Sarah Chen",
    email: "sarah@fintechco.com",
    headline: "Co-founder & CEO at PayBridge | MBA '18",
    bio: "Built PayBridge from 0 to $50M ARR. Passionate about mentoring the next generation of fintech founders.",
    location: "San Francisco, CA",
    graduation_year: 2018,
    current_company: "PayBridge",
    current_title: "Co-founder & CEO",
    industry: "Fintech",
    expertise: ["Fintech", "Fundraising", "Go-to-Market", "Emerging Markets"],
    open_to_mentoring: true,
    hiring: true,
    hiring_roles: ["Product Manager", "Growth Lead"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "a2",
    user_id: "u4",
    role: "alumni",
    full_name: "James Park",
    email: "james@saasventures.com",
    headline: "VP Product at Salesforce | MBA '16",
    bio: "10+ years in B2B SaaS. Love helping MBA students break into product management.",
    location: "San Francisco, CA",
    graduation_year: 2016,
    current_company: "Salesforce",
    current_title: "VP Product",
    industry: "SaaS",
    expertise: ["Product Management", "B2B SaaS", "Enterprise Sales", "OKRs"],
    open_to_mentoring: true,
    hiring: true,
    hiring_roles: ["Product Manager", "Senior PM", "Director of Product"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "a3",
    user_id: "u5",
    role: "alumni",
    full_name: "Aisha Okonkwo",
    email: "aisha@healthai.com",
    headline: "Founder at HealthAI | MD MBA '17",
    bio: "Physician-turned-entrepreneur. Building AI diagnostics for underserved communities.",
    location: "Chicago, IL",
    graduation_year: 2017,
    current_company: "HealthAI",
    current_title: "Founder & CEO",
    industry: "HealthTech",
    expertise: ["Digital Health", "AI/ML", "Healthcare Operations", "Fundraising"],
    open_to_mentoring: true,
    hiring: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockFaculty: FacultyProfile[] = [
  {
    id: "f1",
    user_id: "u6",
    role: "faculty",
    full_name: "Prof. David Kumar",
    email: "dkumar@university.edu",
    headline: "Professor of Finance | Digital Payments Researcher",
    bio: "Researching digital payment infrastructure in emerging markets. Former World Bank consultant.",
    location: "New York, NY",
    department: "Finance",
    research_areas: ["Digital Payments", "Financial Inclusion", "Cryptocurrency", "Central Bank Digital Currencies"],
    courses_taught: ["Fintech & Innovation", "International Finance", "Blockchain & DeFi"],
    open_to_collaboration: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockInvestors: InvestorProfile[] = [
  {
    id: "i1",
    user_id: "u7",
    role: "investor",
    full_name: "Robert Tanaka",
    email: "robert@horizonvc.com",
    headline: "Partner at Horizon Ventures | Fintech & Future of Work",
    bio: "Investing in pre-seed to Series A fintech, payments, and B2B SaaS. MBA alum '10.",
    location: "New York, NY",
    firm: "Horizon Ventures",
    investment_thesis: "Backing founders building financial infrastructure for the next billion users",
    industries: ["Fintech", "Payments", "B2B SaaS", "Future of Work"],
    stages: ["Pre-seed", "Seed", "Series A"],
    ticket_size_min: 250000,
    ticket_size_max: 2000000,
    geography: ["North America", "Southeast Asia", "Africa"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "i2",
    user_id: "u8",
    role: "investor",
    full_name: "Elena Vasquez",
    email: "elena@healthcapital.com",
    headline: "Managing Director at Health Capital | Digital Health",
    bio: "15 years investing in healthcare innovation. Looking for AI-driven healthcare startups.",
    location: "Boston, MA",
    firm: "Health Capital Partners",
    investment_thesis: "AI-enabled solutions that improve health outcomes and reduce costs",
    industries: ["HealthTech", "Digital Health", "AI/ML", "BioTech"],
    stages: ["Seed", "Series A", "Series B"],
    ticket_size_min: 500000,
    ticket_size_max: 5000000,
    geography: ["North America", "Europe"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockRecommendationsForPriya: Recommendation[] = [
  {
    profile: mockAlumni[0],
    matchScore: 96,
    reason: "Sarah built a fintech company in emerging markets — identical to your startup vision. She's actively mentoring and open to meeting founders.",
    matchType: "mentor",
    sharedInterests: ["Fintech", "Emerging Markets", "Fundraising"],
  },
  {
    profile: mockInvestors[0],
    matchScore: 91,
    reason: "Robert invests in fintech and payments at pre-seed stage. His thesis on 'financial infrastructure for the next billion' matches your career goal.",
    matchType: "invest",
    sharedInterests: ["Fintech", "Payments", "Emerging Markets"],
  },
  {
    profile: mockFaculty[0],
    matchScore: 88,
    reason: "Prof. Kumar is actively researching digital payments in emerging markets — a direct research collaboration opportunity.",
    matchType: "research",
    sharedInterests: ["Digital Payments", "Emerging Markets"],
  },
];

export const mockRecommendationsForMarcus: Recommendation[] = [
  {
    profile: mockAlumni[2],
    matchScore: 94,
    reason: "Aisha is a physician-turned-founder who built an AI health diagnostics startup — her journey mirrors exactly what you're pursuing.",
    matchType: "mentor",
    sharedInterests: ["HealthTech", "AI/ML", "Clinical Background"],
  },
  {
    profile: mockInvestors[1],
    matchScore: 89,
    reason: "Elena actively invests in AI-driven healthcare startups at seed stage. Her portfolio aligns with your digital health focus.",
    matchType: "invest",
    sharedInterests: ["HealthTech", "AI/ML", "Digital Health"],
  },
];

export const adminMetrics = {
  totalUsers: 2847,
  students: 1204,
  alumni: 1389,
  faculty: 186,
  investors: 68,
  mentorSessions: 342,
  jobPlacements: 89,
  startupsFunded: 14,
  fundingRaised: 28500000,
  activeConnections: 1847,
  introductionsSent: 523,
  engagementScore: 78,
};
